version: "3.8"

services:
  backend:
    build: ./Backend-air-monitoring
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  frontend:
    build: ./Front-air-monitoring
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
